spring.application.name=testing-system
spring.datasource.url=jdbc:mysql://localhost:3306/dtn2602_buoi1
spring.datasource.username=root
spring.datasource.password=823067Nd
spring.jpa.hibernate.ddl-auto=none